services:
  - type: web
    name: splitsmart
    env: node
    buildCommand: npm run build
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000